version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/rdoxlogin
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: ubuntu